In [7]:
import pandas as pd

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [9]:
!git clone https://github.com/UJJWAL1217/Team-48-Crop-Prediction.git

Cloning into 'Team-48-Crop-Prediction'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 121 (delta 34), reused 19 (delta 5), pack-reused 56 (from 1)
Receiving objects: 100% (121/121), 63.65 MiB | 40.19 MiB/s, done.
Resolving deltas: 100% (53/53), done.

In [10]:
import os
os.chdir("Team-48-Crop-Prediction/Dataset")

In [11]:
!ls

Crop_recommendation.csv

In [12]:
data = pd.read_csv("Crop_recommendation.csv")

In [13]:
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [14]:
data.shape

(2200, 8)

In [15]:
data.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

Spliting labels and features

In [16]:
x = data.iloc[:,:-1] #features
y = data.iloc[:,-1] #labels

In [17]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [18]:
x_train.head()

        N   P   K  temperature   humidity        ph    rainfall
1656   17  16  14    16.396243  92.181519  6.625539  102.944161
752    37  79  19    27.543848  69.347863  7.143943   69.408782
892     7  73  25    27.521856  63.132153  7.288057   45.208411
1041  101  70  48    25.360592  75.031933  6.012697  116.553145
1179    0  17  30    35.474783  47.972305  6.279134   97.790725

In [19]:
y_train.head()

1656       orange
752     blackgram
892        lentil
1041       banana
1179        mango
Name: label, dtype: object

In [20]:
model = RandomForestClassifier() #multiple disition tree

In [21]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [22]:
predictions = model.predict(x_test)

In [23]:
accuracy = model.score(x_test,y_test)

In [24]:
print("Accuracy:", accuracy)

Accuracy: 0.9931818181818182

In [25]:
new_featurees = [[36,58,25,28.66024,59.31891,8.399136,36.9263]]
predicted_crop = model.predict(new_featurees)
print("Predicted Crop:", predicted_crop)

Predicted Crop: ['mothbeans']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [26]:
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

In [27]:
from google.colab import files
files.download("model.pkl")