In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [ ]:
import pandas as pd
from io import StringIO

csv_text = """
age,gender,review,education,purchased
56,Male,Good,UG,Yes
46,Female,Average,PG,No
32,Female,Excellent,UG,Yes
25,Female,Poor,School,No
38,Female,Good,UG,Yes
56,Female,Good,PhD,No
36,Female,Average,School,Yes
40,Male,Good,PG,No
28,Male,Excellent,UG,Yes
28,Male,Poor,School,No
41,Male,Average,PG,Yes
53,Male,Excellent,PhD,No
57,Male,Average,UG,Yes
41,Female,Excellent,UG,No
20,Female,Good,School,Yes
39,Female,Good,UG,No
19,Male,Average,PG,Yes
41,Male,Poor,School,No
47,Male,Good,PhD,Yes
55,Female,Excellent,UG,No
19,Female,Average,School,Yes
42,Female,Good,UG,No
31,Female,Good,PG,Yes
21,Male,Poor,School,No
43,Male,Excellent,UG,Yes
33,Male,Average,PhD,No
29,Female,Good,UG,Yes
37,Male,Excellent,School,No
23,Female,Poor,PG,Yes
54,Female,Good,UG,No
38,Male,Average,School,Yes
57,Male,Good,PhD,No
36,Female,Excellent,UG,Yes
29,Female,Poor,School,No
44,Male,Good,PG,Yes
20,Female,Average,UG,No
41,Male,Excellent,PhD,Yes
35,Female,Good,School,No
52,Male,Poor,UG,Yes
46,Female,Average,PG,No
27,Male,Good,School,Yes
59,Male,Excellent,UG,No
24,Female,Good,PhD,Yes
34,Male,Average,School,No
45,Female,Poor,UG,Yes
22,Male,Good,PG,No
39,Female,Excellent,UG,Yes
31,Male,Average,School,No
48,Female,Good,PhD,Yes
26,Male,Poor,UG,No
50,Female,Excellent,PG,Yes
28,Male,Good,School,No
43,Female,Average,UG,Yes
37,Male,Good,PhD,No
55,Female,Poor,School,Yes
30,Male,Excellent,UG,No
42,Female,Good,PG,Yes
33,Male,Average,School,No
47,Female,Good,PhD,Yes
21,Male,Excellent,UG,No
40,Female,Poor,School,Yes
58,Male,Good,PG,No
29,Female,Average,UG,Yes
36,Male,Excellent,PhD,No
44,Female,Good,School,Yes
32,Male,Poor,UG,No
53,Female,Excellent,PG,Yes
25,Male,Good,School,No
39,Female,Average,UG,Yes
48,Male,Good,PhD,No
27,Female,Poor,School,Yes
41,Male,Excellent,UG,No
34,Female,Good,PG,Yes
52,Male,Average,School,No
30,Female,Good,PhD,Yes
57,Male,Poor,UG,No
22,Female,Excellent,PG,Yes
49,Male,Good,School,No
38,Female,Average,UG,Yes
26,Male,Good,PhD,No
54,Female,Poor,School,Yes
31,Male,Excellent,UG,No
45,Female,Good,PG,Yes
28,Male,Average,School,No
43,Female,Good,PhD,Yes
37,Male,Poor,UG,No
50,Female,Excellent,PG,Yes
24,Male,Good,School,No
46,Female,Average,UG,Yes
33,Male,Good,PhD,No
59,Female,Poor,School,Yes
29,Male,Excellent,UG,No
41,Female,Good,PG,Yes
35,Male,Average,School,No
48,Female,Good,PhD,Yes
27,Male,Poor,UG,No
53,Female,Excellent,PG,Yes
"""

data = pd.read_csv(StringIO(csv_text))
data.head()

   age  gender     review education purchased
0   56    Male       Good        UG       Yes
1   46  Female    Average        PG        No
2   32  Female  Excellent        UG       Yes
3   25  Female       Poor    School        No
4   38  Female       Good        UG       Yes

In [ ]:
df = data.copy()

In [ ]:
df.head(34)

       review education purchased
0        Good        UG       Yes
1     Average        PG        No
2   Excellent        UG       Yes
3        Poor    School        No
4        Good        UG       Yes
5        Good       PhD        No
6     Average    School       Yes
7        Good        PG        No
8   Excellent        UG       Yes
9        Poor    School        No
10    Average        PG       Yes
11  Excellent       PhD        No
12    Average        UG       Yes
13  Excellent        UG        No
14       Good    School       Yes
15       Good        UG        No
16    Average        PG       Yes
17       Poor    School        No
18       Good       PhD       Yes
19  Excellent        UG        No
20    Average    School       Yes
21       Good        UG        No
22       Good        PG       Yes
23       Poor    School        No
24  Excellent        UG       Yes
25    Average       PhD        No
26       Good        UG       Yes
27  Excellent    School        No
28       Poor        PG       Yes
29       Good        UG        No
30    Average    School       Yes
31       Good       PhD        No
32  Excellent        UG       Yes
33       Poor    School        No

Here we are going to apply `one hotencoding` in `gender` column , `ordinal encoding` in `review, education` and `label encoder` in `purchesed` column

` Ordinal Encoding` -> There are more levels of orders not just 2

In [ ]:
df1 = df[['review','education','purchased']]

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head(4)

      review education purchased
0       Good        UG       Yes
1    Average        PG        No
2  Excellent        UG       Yes
3       Poor    School        No

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:2] , df.iloc[:, -1], test_size= 0.2)

In [ ]:
x_test

       review education
4        Good        UG
68    Average        UG
16    Average        PG
44       Poor        UG
21       Good        UG
80       Poor    School
12    Average        UG
57    Average    School
81  Excellent        UG
41  Excellent        UG
34       Good        PG
26       Good        UG
25    Average       PhD
77       Good    School
43    Average    School
7        Good        PG
6     Average    School
10    Average        PG
65       Poor        UG
33       Poor    School

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
 oe = OrdinalEncoder(categories=[['Poor','Average','Good','Excellent'],['School','UG','PG','PhD']])

In [ ]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good', 'Excellent'],
                           ['School', 'UG', 'PG', 'PhD']])

In [ ]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [ ]:
x_test

array([[2., 1.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [3., 1.],
       [3., 1.],
       [2., 2.],
       [2., 1.],
       [1., 3.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [1., 0.],
       [1., 2.],
       [0., 1.],
       [0., 0.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good', 'Excellent'], dtype=object),
 array(['School', 'UG', 'PG', 'PhD'], dtype=object)]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder() # only apply on output column

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_test

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [2]:
from google.colab import files
files.download('triyal.ipynb')

FileNotFoundError: Cannot find file: triyal.ipynb