In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import xgboost as xgb

In [20]:
data = pd.read_csv('/content/loan_sanction_test.csv')

In [21]:
df = data.copy()

In [22]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [23]:
df.shape

(367, 12)

In [24]:
df.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [25]:
df["Gender"].isnull().sum()
df["Gender"].value_counts(dropna=False)

Gender
Male      286
Female     70
NaN        11
Name: count, dtype: int64

# Handling missing valuse

` df = df.dropna(subset=["gender"]) `
if rows are less , remove those rows

In [26]:
# for gender
df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

/tmp/ipython-input-1435588280.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

In [27]:
df["Gender"].map({"Male": 1, "Female": 0})

0      1
1      1
2      1
3      1
4      1
      ..
362    1
363    1
364    1
365    1
366    1
Name: Gender, Length: 367, dtype: int64

In [12]:
# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Gender'])

In [ ]:
# df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [33]:
ohe_sex = OneHotEncoder(sparse_output=False , handle_unknown='ignore')
x_train_sex = ohe_sex.fit_transform(x_train[['Gender']])

NameError: name 'x_train' is not defined

In [30]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,1.0,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,1.0,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,1.0,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,1.0,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,1.0,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

# Working in Dependents column

In [ ]:
df['Dependents'].isnull().sum()
df['Dependents'].value_counts(dropna=False)

Dependents
0      200
2       59
1       58
3+      40
NaN     10
Name: count, dtype: int64

In [ ]:
mask = df["Dependents"].isnull()

df.loc[mask, "Dependents"] = "0"

In [ ]:
df['Dependents'] = df['Dependents'].str.replace('+', '')
df['Dependents'].fillna('0', inplace=True)
df['Dependents'] = df['Dependents'].astype(int)
df['Dependents'].value_counts()

/tmp/ipython-input-660782228.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Dependents'].fillna('0', inplace=True)

Dependents
0    210
2     59
1     58
3     40
Name: count, dtype: int64

In [ ]:
print(df["Dependents"].dtype)

int64

In [ ]:
df.loc[df["Self_Employed"].isnull(),"Self_Employed"]

8      NaN
11     NaN
13     NaN
36     NaN
72     NaN
89     NaN
142    NaN
161    NaN
168    NaN
175    NaN
192    NaN
243    NaN
255    NaN
259    NaN
276    NaN
278    NaN
285    NaN
287    NaN
294    NaN
297    NaN
301    NaN
323    NaN
326    NaN
Name: Self_Employed, dtype: object

In [ ]:
mask = df["Self_Employed"].isnull()

In [ ]:
df["Self_Employed"].isnull().sum()
df["Self_Employed"].value_counts(dropna=False)

Self_Employed
No     307
Yes     37
NaN     23
Name: count, dtype: int64

In [ ]:
df["Self_Employed"].fillna("No", inplace=True)

/tmp/ipython-input-3952120174.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Self_Employed"].fillna("No", inplace=True)

In [ ]:
df["LoanAmount"][df["LoanAmount"].isnull()]

78    NaN
101   NaN
188   NaN
247   NaN
289   NaN
Name: LoanAmount, dtype: float64

In [ ]:
df['LoanAmount'].value_counts(dropna=False)

LoanAmount
150.0    12
125.0    11
110.0    10
100.0     9
90.0      9
         ..
197.0     1
85.0      1
60.0      1
76.0      1
98.0      1
Name: count, Length: 145, dtype: int64

# Working on LoanAmount
We are going to replace null values with median values

In [ ]:
df["LoanAmount"].fillna(df["LoanAmount"].median(), inplace=True)

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [ ]:
df['Loan_Amount_Term'].value_counts(dropna = False)

Loan_Amount_Term
360.0    311
180.0     22
480.0      8
300.0      7
NaN        6
240.0      4
84.0       3
60.0       1
12.0       1
350.0      1
36.0       1
120.0      1
6.0        1
Name: count, dtype: int64

In [ ]:
df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].median(), inplace=True)

/tmp/ipython-input-23078053.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].median(), inplace=True)

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       29
Property_Area         0
dtype: int64

In [ ]:
df["Credit_History"].value_counts(dropna=False)

Credit_History
1.0    279
0.0     59
NaN     29
Name: count, dtype: int64

In [ ]:
df.loc[df["Credit_History"].isnull(), "Credit_History"]

3     NaN
12    NaN
26    NaN
28    NaN
45    NaN
90    NaN
99    NaN
104   NaN
115   NaN
139   NaN
143   NaN
164   NaN
177   NaN
179   NaN
185   NaN
202   NaN
220   NaN
259   NaN
262   NaN
265   NaN
282   NaN
286   NaN
305   NaN
329   NaN
336   NaN
351   NaN
358   NaN
360   NaN
364   NaN
Name: Credit_History, dtype: float64

In [ ]:
import numpy as np
df['Credit_History'] = df['Credit_History'].fillna(
    df.groupby('Self_Employed')['Credit_History'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

In [ ]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

# Now spliting labels and features

In [ ]:
df.head(1)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban

In [ ]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,1.0,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,1.0,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural

# One hotencoding

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [ ]:

x = df.drop(["Loan_ID", "LoanAmount"] , axis = 1)
y = df["LoanAmount"]

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [ ]:
x_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,Loan_Amount_Term,Credit_History,Property_Area
342,1,NaN,3,NaN,No,3522,0,180.0,1.0,Rural
202,1,NaN,0,NaN,No,3016,1300,360.0,1.0,Urban
75,1,NaN,0,NaN,No,3583,3435,360.0,1.0,Urban
84,1,NaN,0,NaN,No,4456,0,180.0,0.0,Semiurban
355,1,NaN,3,NaN,No,7603,1213,360.0,1.0,Urban

In [ ]:
model = RandomForestClassifier()
model.fit(x_train, y_train)

ValueError: could not convert string to float: 'Not Graduate'

In [ ]:
y_pres = model.predict(x_test)

In [ ]:
model.score(x_test, y_test)

0.05405405405405406

In [ ]:
accuracy_score(y_test, y_pres)

0.05405405405405406

In [ ]:
model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, learning_rate=0.05)
model.fit(x_train, y_train)

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:Married: object, Education: object, Self_Employed: object, Property_Area: object